// Generated by scripts/generate_types.py from backend/app/schemas.py.
// Do not edit by hand: run `python scripts/generate_types.py` instead.


export type Severity = "info" | "warning" | "blocker";

export type CandidateKind = "logistic_regression" | "xgboost" | "xgboost_augmented" | "age_baseline";

export type FaultDuration = "persistent" | "transient";

export type FaultKind = "dropout" | "stuck" | "drift";

export type Partition = "out_of_fold" | "holdout";

export type SelectionOutcome = "qualified" | "none_qualified";


export interface AcceptanceCriteria {
  min_detection_fraction: number;
  max_early_alarm_burden: number;
  min_useful_lead: number;
  horizon_cycles: number;
}

export interface AlertEpisode {
  start_cycle: number;
  end_cycle: number;
  start_rul: number;
  end_rul: number;
  still_open_at_failure?: boolean;
  /** Highest score reached while the alert was active. */
  peak_score?: number | null;
}

export interface AlertExplanation {
  equipment_id: string;
  cycle: number;
  score: number;
  base_value?: number | null;
  contributions?: ShapContribution[];
  available?: boolean;
  note?: string;
}

export interface AlertMetrics {
  engines: number;
  detected: number;
  late: number;
  missed: number;
  detection_fraction: number;
  detection_ci: WilsonInterval;
  /** Fraction of eligible cycles (rul > transition band) spent in alarm. */
  early_alarm_burden: number;
  new_episodes_per_1000: number;
  median_lead_time: number | null;
  eligible_cycles: number;
  scored_cycles: number;
}

export interface CalibrationReport {
  candidate: CandidateKind;
  config_id: string;
  partition: Partition;
  brier: number;
  bins: ReliabilityBin[];
  note?: string;
}

export interface CandidateConfig {
  candidate: CandidateKind;
  config_id: string;
  params?: Record<string, unknown>;
  uses_sensors?: boolean;
  description?: string;
}

export interface CandidateVerdict {
  candidate: CandidateKind;
  config_id: string;
  threshold: number;
  clean: AlertMetrics;
  passes_clean: boolean;
  required_scenarios: number;
  required_passed: number;
  passes_all_required: boolean;
  mean_detection_required: number;
  worst_detection_required: number;
  worst_scenario_id?: string | null;
  /** Full measures for the worst required scenario. Carrying the interval as well as the point estimate keeps a small drop from being read as real when the sample cannot support the comparison. */
  worst_metrics?: AlertMetrics | null;
  /** Required scenarios that fell short of the criteria. */
  failing_scenarios?: string[];
  qualifies?: boolean;
  notes?: string[];
}

export interface CopilotAnswer {
  text: string;
  tool_calls?: ToolInvocation[];
  citations?: string[];
  claims?: NumericClaim[];
  unverified_claims?: number;
  /** The tool-call budget was exhausted. */
  truncated?: boolean;
  /** No LLM was available; a deterministic answer was returned. */
  degraded?: boolean;
}

export interface CopilotRequest {
  question: string;
  candidate?: CandidateKind | null;
  scenario_id?: string | null;
}

export interface DatasetProfile {
  dataset_id: string;
  source: string;
  data_hash: string;
  row_count: number;
  equipment_count: number;
  min_cycles: number;
  max_cycles: number;
  median_cycles: number;
  sensors: SensorProfile[];
  findings?: ProfileFinding[];
  positive_label_fraction?: number | null;
  usable?: boolean;
}

export interface EngineOutcome {
  equipment_id: string;
  detected: boolean;
  late: boolean;
  missed: boolean;
  lead_time?: number | null;
  episode_count?: number;
}

export interface EvidenceBundle {
  schema_version?: number;
  generated_at?: string;
  config: Record<string, unknown>;
  config_fingerprint: string;
  git_commit?: string | null;
  profile: DatasetProfile;
  splits: SplitAssignment;
  candidates: CandidateConfig[];
  development_selection: SelectionResult;
  final_evaluation?: SelectionResult | null;
  scenario_results: ScenarioResult[];
  calibration?: CalibrationReport[];
  replay_series?: ReplaySeries[];
  explanations?: AlertExplanation[];
  runs?: RunRecord[];
  reproducibility?: ReproducibilityCheck | null;
  limitations?: string[];
}

export interface FaultSpec {
  kind: FaultKind;
  duration: FaultDuration;
  sensor: string;
  /** Cycles before failure at which the fault begins. None means the onset was drawn at random from a recorded seed. */
  onset_before_failure?: number | null;
  /** Drift magnitude in training standard deviations. */
  severity_sd?: number | null;
  sign?: number | null;
  ramp_cycles?: number | null;
  /** Transient length in cycles. */
  length?: number | null;
  seed?: number | null;
}

export interface NumericClaim {
  text: string;
  value: number;
  verified: boolean;
  matched_metric?: string | null;
}

export interface ProfileFinding {
  code: string;
  severity: Severity;
  message: string;
  detail?: Record<string, unknown>;
}

export interface ReliabilityBin {
  lower: number;
  upper: number;
  count: number;
  mean_predicted: number;
  observed_rate: number;
}

export interface ReplayPoint {
  cycle: number;
  rul: number;
  score: number;
  alert: boolean;
  sensor_clean?: number | null;
  sensor_faulted?: number | null;
}

export interface ReplaySeries {
  equipment_id: string;
  candidate: CandidateKind;
  config_id: string;
  scenario_id: string;
  threshold: number;
  fault?: FaultSpec | null;
  /** Cycles before failure at which the fault actually began on this history. A random-onset scenario resolves to a different cycle per engine. */
  fault_onset_rul?: number | null;
  fault_affected_cycles?: number;
  points: ReplayPoint[];
  episodes: AlertEpisode[];
  outcome: EngineOutcome;
  failure_cycle: number;
}

export interface ReproducibilityCheck {
  run_id: string;
  repeat_run_id: string;
  tolerance: number;
  max_absolute_difference: number;
  metrics_compared: number;
  reproduced: boolean;
}

export interface RunRecord {
  run_id: string;
  kind: "profile" | "training" | "fault_matrix" | "selection" | "final_evaluation" | "export";
  created_at?: string;
  config_fingerprint: string;
  data_hash?: string | null;
  seed?: number | null;
  git_commit?: string | null;
  parent_run_id?: string | null;
  params?: Record<string, unknown>;
  metrics?: Record<string, number>;
  artifacts?: Record<string, string>;
  notes?: string[];
}

export interface ScenarioResult {
  scenario_id: string;
  candidate: CandidateKind;
  config_id: string;
  partition: Partition;
  threshold: number;
  fault?: FaultSpec | null;
  metrics: AlertMetrics;
  /** Part of the bounded set used for selection. */
  required?: boolean;
  run_id?: string | null;
}

export interface SelectionResult {
  outcome: SelectionOutcome;
  criteria: AcceptanceCriteria;
  ranked: CandidateVerdict[];
  recommended?: CandidateVerdict | null;
  partition?: Partition;
  notes?: string[];
  /** Pairs whose detection intervals overlap, so the ordering is not established by the data. */
  uncertain_comparisons?: string[];
}

export interface SensorProfile {
  name: string;
  mean: number | null;
  std: number | null;
  minimum: number | null;
  maximum: number | null;
  missing_fraction: number;
  constant: boolean;
  /** Eligible for fault testing. */
  varies: boolean;
}

export interface ShapContribution {
  feature: string;
  value: number | null;
  contribution: number;
}

export interface SplitAssignment {
  holdout: string[];
  development: string[];
  /** Validation engines per fold. */
  folds: string[][];
  seed: number;
  config_fingerprint: string;
}

export interface ToolInvocation {
  name: string;
  arguments?: Record<string, unknown>;
  ok?: boolean;
  error?: string | null;
  duration_ms?: number | null;
  run_ids?: string[];
}

export interface WilsonInterval {
  lower: number;
  upper: number;
  level?: number;
}
