// Generated by scripts/generate_types.py from backend/app/schemas.py.
// Do not edit by hand: run `python scripts/generate_types.py` instead.


export type Severity = "info" | "warning" | "blocker";

export type FaultDuration = "persistent" | "transient";

export type FaultKind = "dropout" | "stuck" | "drift";

export type PilotDecision = "supervised_trial" | "revise_model" | "collect_data" | "stop";

export type JobStatus = "queued" | "running" | "cancelling" | "completed" | "cancelled" | "timed_out" | "interrupted" | "failed";

export type CandidateKind = "logistic_regression" | "xgboost" | "xgboost_augmented" | "age_baseline";

export type Partition = "out_of_fold" | "holdout";

export type SelectionOutcome = "qualified" | "none_qualified";


export interface AcceptanceCriteria {
  min_detection_fraction: number;
  max_early_alarm_burden: number;
  min_useful_lead: number;
  horizon_cycles: number;
}

export interface AlertEpisode {
  start_cycle: number;
  end_cycle: number;
  start_rul: number;
  end_rul: number;
  still_open_at_failure?: boolean;
  /** Highest score reached while the alert was active. */
  peak_score?: number | null;
}

export interface AlertExplanation {
  equipment_id: string;
  cycle: number;
  score: number;
  base_value?: number | null;
  contributions?: ShapContribution[];
  available?: boolean;
  note?: string;
  candidate?: string | null;
  partition?: Partition;
}

export interface AlertMetrics {
  engines: number;
  detected: number;
  late: number;
  missed: number;
  detection_fraction: number;
  detection_ci: WilsonInterval;
  /** Fraction of eligible cycles spent in alarm; unavailable with no eligible cycles. */
  early_alarm_burden: number | null;
  new_episodes_per_1000: number;
  median_lead_time: number | null;
  eligible_cycles: number;
  scored_cycles: number;
}

export interface CalibrationReport {
  candidate: CandidateKind;
  config_id: string;
  partition: Partition;
  brier: number;
  bins: ReliabilityBin[];
  note?: string;
}

export interface CandidateConfig {
  candidate: CandidateKind;
  config_id: string;
  params?: Record<string, unknown>;
  uses_sensors?: boolean;
  description?: string;
}

export interface CandidateVerdict {
  candidate: CandidateKind;
  config_id: string;
  threshold: number;
  clean: AlertMetrics;
  passes_clean: boolean;
  required_scenarios: number;
  required_passed: number;
  passes_all_required: boolean;
  mean_detection_required: number;
  worst_detection_required: number;
  worst_scenario_id?: string | null;
  /** Full measures for the worst required scenario. Carrying the interval as well as the point estimate keeps a small drop from being read as real when the sample cannot support the comparison. */
  worst_metrics?: AlertMetrics | null;
  /** Required scenarios that fell short of the criteria. */
  failing_scenarios?: string[];
  qualifies?: boolean;
  notes?: string[];
  worst_burden_required?: number | null;
  worst_burden_scenario_id?: string | null;
  coverage_complete?: boolean | null;
}

export interface ColumnMapping {
  equipment_id: string;
  cycle_index: string;
  sensors: string[];
  failure_cycle?: string | null;
  ignored?: string[];
  inferred?: boolean;
  /** Columns the profiler could not assign confidently. The engineer confirms these before training. */
  ambiguous?: string[];
}

export interface CopilotAnswer {
  text: string;
  tool_calls?: ToolInvocation[];
  citations?: string[];
  claims?: NumericClaim[];
  unverified_claims?: number;
  /** The tool-call budget was exhausted. */
  truncated?: boolean;
  /** No LLM was available; a deterministic answer was returned. */
  degraded?: boolean;
}

export interface CopilotRequest {
  question: string;
  candidate?: CandidateKind | null;
  scenario_id?: string | null;
}

export interface DatasetConfirmation {
  mapping: ColumnMapping;
  complete_histories?: boolean;
}

export interface DatasetProfile {
  dataset_id: string;
  source: string;
  data_hash: string;
  row_count: number;
  equipment_count: number;
  min_cycles: number;
  max_cycles: number;
  median_cycles: number;
  sensors: SensorProfile[];
  findings?: ProfileFinding[];
  positive_label_fraction?: number | null;
  usable?: boolean;
}

export interface DatasetRegistration {
  dataset_id: string;
  name: string;
  source: "synthetic" | "upload";
  columns: string[];
  preview: Record<string, unknown>[];
  row_count: number;
  mapping?: ColumnMapping | null;
  complete_histories?: boolean;
  confirmed?: boolean;
  profile?: DatasetProfile | null;
  splits?: SplitAssignment | null;
}

export interface DecisionReport {
  title: string;
  summary: string;
  fault_summary: string;
  augmentation_summary: string;
  unaugmented?: CandidateVerdict | null;
  augmented?: CandidateVerdict | null;
  limitations: string[];
  guide: GuideAnswer[];
  inspected_candidate?: string | null;
  partition?: Partition;
}

export interface EngineOutcome {
  equipment_id: string;
  detected: boolean;
  late: boolean;
  missed: boolean;
  lead_time?: number | null;
  episode_count?: number;
}

export interface EvidenceBundle {
  schema_version?: number;
  experiment_id?: string | null;
  dataset_id?: string | null;
  source_digest?: string | null;
  dependency_versions?: Record<string, string>;
  confirmed_mapping?: ColumnMapping | null;
  complete_histories_confirmed?: boolean | null;
  holdout_status?: string;
  generated_at?: string;
  config: Record<string, unknown>;
  config_fingerprint: string;
  git_commit?: string | null;
  profile: DatasetProfile;
  splits: SplitAssignment;
  candidates: CandidateConfig[];
  development_selection: SelectionResult;
  final_evaluation?: SelectionResult | null;
  scenario_results: ScenarioResult[];
  calibration?: CalibrationReport[];
  replay_series?: ReplaySeries[];
  explanations?: AlertExplanation[];
  runs?: RunRecord[];
  reproducibility?: ReproducibilityCheck | null;
  limitations?: string[];
  protocol?: ExperimentProtocol | null;
  pilot_brief?: PilotBrief | null;
  paired_comparisons?: PairedComparison[];
  frozen_model?: FrozenModelRecord | null;
  validation?: ValidationRecord | null;
  pilot_review?: PilotReviewRecord | null;
}

export interface ExperimentCreate {
  dataset_id: string;
  min_detection_fraction?: number;
  max_early_alarm_burden?: number;
  protocol?: ExperimentProtocol | null;
  pilot_brief?: PilotBrief | null;
}

export interface ExperimentProtocol {
  version?: number;
  min_useful_lead?: number;
  horizon_cycles?: number;
  transition_band_end?: number;
  min_detection_fraction?: number;
  max_early_alarm_burden?: number;
  scenarios?: FaultScenario[];
  base_seed?: number;
}

export interface ExperimentRecord {
  experiment_id: string;
  dataset_id: string;
  name: string;
  source: "synthetic" | "upload";
  status: JobStatus;
  created_at: number;
  started_at?: number | null;
  finished_at?: number | null;
  elapsed_seconds?: number;
  stage?: string;
  completed_work?: number;
  total_work?: number | null;
  work_unit?: string;
  error?: string | null;
  config: Record<string, unknown>;
  config_fingerprint: string;
  data_hash: string;
  source_digest: string;
  job_kind?: "development" | "freeze" | "validation";
  parent_experiment_id?: string | null;
  operation_id?: string | null;
  pilot_brief?: PilotBrief | null;
}

export interface FaultScenario {
  fault: FaultSpec;
  required?: boolean;
}

export interface FaultSpec {
  kind: FaultKind;
  duration: FaultDuration;
  sensor: string;
  /** Cycles before failure at which the fault begins. None means the onset was drawn at random from a recorded seed. */
  onset_before_failure?: number | null;
  /** Drift magnitude in training standard deviations. */
  severity_sd?: number | null;
  sign?: number | null;
  ramp_cycles?: number | null;
  /** Transient length in cycles. */
  length?: number | null;
  seed?: number | null;
}

export interface FrozenModelRecord {
  freeze_id: string;
  experiment_id: string;
  job_id: string;
  candidate: string;
  status?: string;
  manifest?: Record<string, unknown>;
  artifact_digest?: string | null;
  manifest_digest?: string | null;
  created_at: number;
  error?: string | null;
}

export interface GuideAnswer {
  question: string;
  answer: string;
  link: string;
  link_label: string;
}

export interface NumericClaim {
  text: string;
  value: number;
  verified: boolean;
  matched_metric?: string | null;
}

export interface PairedComparison {
  first: string;
  second: string;
  kind: "selected" | "matched_augmentation";
  engines: number;
  scenarios: number;
  resamples?: number;
  seed: number;
  detection_delta: number;
  detection_interval: number[];
  burden_delta?: number | null;
  burden_interval?: number[] | null;
  note?: string;
}

export interface PilotAgreementCreate {
  brief: PilotBrief;
  single_family_confirmed: boolean;
  failure_labels_checked: boolean;
  representative_data_confirmed: boolean;
  protocol_agreed: boolean;
}

export interface PilotAgreementRecord {
  brief: PilotBrief;
  single_family_confirmed: boolean;
  failure_labels_checked: boolean;
  representative_data_confirmed: boolean;
  protocol_agreed: boolean;
  agreement_id: string;
  experiment_id: string;
  dataset_id: string;
  data_source: "synthetic" | "upload";
  data_hash: string;
  config_fingerprint: string;
  source_digest: string;
  candidate: string;
  created_at: number;
}

export interface PilotBrief {
  equipment_family?: string;
  reviewing_engineer?: string;
  current_procedure?: string;
  intended_decision?: string;
  success_measure?: string;
  data_classification?: "simulated" | "field" | "unverified";
}

export interface PilotOutcomeCreate {
  reviewing_engineer: string;
  decision: PilotDecision;
  decision_changed: boolean;
  observations: string;
  baseline_review_minutes?: number | null;
  sidekick_review_minutes?: number | null;
  evidence_reviewed: boolean;
}

export interface PilotOutcomeRecord {
  reviewing_engineer: string;
  decision: PilotDecision;
  decision_changed: boolean;
  observations: string;
  baseline_review_minutes?: number | null;
  sidekick_review_minutes?: number | null;
  evidence_reviewed: boolean;
  review_id: string;
  agreement_id: string;
  experiment_id: string;
  validation_id: string;
  freeze_id: string;
  artifact_digest: string;
  final_qualifies: boolean;
  review_minutes_saved?: number | null;
  created_at: number;
}

export interface PilotReviewRecord {
  agreement: PilotAgreementRecord;
  outcome?: PilotOutcomeRecord | null;
}

export interface PilotState {
  record?: PilotReviewRecord | null;
  agreement?: PilotAgreementRecord | null;
  outcome?: PilotOutcomeRecord | null;
  phase: "agreement" | "evaluation" | "review" | "complete";
  agreement_blocked?: string | null;
  review_blocked?: string | null;
  final_qualifies?: boolean | null;
}

export interface ProfileFinding {
  code: string;
  severity: Severity;
  message: string;
  detail?: Record<string, unknown>;
}

export interface ReliabilityBin {
  lower: number;
  upper: number;
  count: number;
  mean_predicted: number;
  observed_rate: number;
}

export interface ReplayPoint {
  cycle: number;
  rul: number;
  score: number;
  alert: boolean;
  sensor_clean?: number | null;
  sensor_faulted?: number | null;
}

export interface ReplaySeries {
  equipment_id: string;
  candidate: CandidateKind;
  config_id: string;
  scenario_id: string;
  threshold: number;
  fault?: FaultSpec | null;
  /** Cycles before failure at which the fault actually began on this history. A random-onset scenario resolves to a different cycle per engine. */
  fault_onset_rul?: number | null;
  fault_affected_cycles?: number;
  points: ReplayPoint[];
  episodes: AlertEpisode[];
  outcome: EngineOutcome;
  failure_cycle: number;
  partition?: Partition;
  representative_reason?: string | null;
}

export interface ReproducibilityCheck {
  run_id: string;
  repeat_run_id: string;
  tolerance: number;
  max_absolute_difference: number;
  metrics_compared: number;
  reproduced: boolean;
}

export interface RunRecord {
  run_id: string;
  kind: "profile" | "training" | "fault_matrix" | "selection" | "final_evaluation" | "export";
  created_at?: string;
  config_fingerprint: string;
  data_hash?: string | null;
  seed?: number | null;
  git_commit?: string | null;
  parent_run_id?: string | null;
  params?: Record<string, unknown>;
  metrics?: Record<string, number>;
  artifacts?: Record<string, string>;
  notes?: string[];
}

export interface ScenarioResult {
  scenario_id: string;
  candidate: CandidateKind;
  config_id: string;
  partition: Partition;
  threshold: number;
  fault?: FaultSpec | null;
  metrics: AlertMetrics;
  /** Part of the bounded set used for selection. */
  required?: boolean;
  run_id?: string | null;
  expected_engines?: number | null;
  coverage_complete?: boolean | null;
  coverage_notes?: string[];
}

export interface SelectionResult {
  outcome: SelectionOutcome;
  criteria: AcceptanceCriteria;
  ranked: CandidateVerdict[];
  recommended?: CandidateVerdict | null;
  partition?: Partition;
  notes?: string[];
  /** Pairs whose detection intervals overlap, so the ordering is not established by the data. */
  uncertain_comparisons?: string[];
}

export interface SensorProfile {
  name: string;
  mean: number | null;
  std: number | null;
  minimum: number | null;
  maximum: number | null;
  missing_fraction: number;
  constant: boolean;
  /** Eligible for fault testing. */
  varies: boolean;
}

export interface ShapContribution {
  feature: string;
  value: number | null;
  contribution: number;
}

export interface SplitAssignment {
  holdout: string[];
  development: string[];
  /** Validation engines per fold. */
  folds: string[][];
  seed: number;
  config_fingerprint: string;
}

export interface ToolInvocation {
  name: string;
  arguments?: Record<string, unknown>;
  ok?: boolean;
  error?: string | null;
  duration_ms?: number | null;
  run_ids?: string[];
}

export interface ValidationCreate {
  untouched_confirmed: boolean;
}

export interface ValidationRecord {
  validation_id: string;
  experiment_id: string;
  freeze_id: string;
  job_id: string;
  status?: string;
  untouched_confirmed: boolean;
  exposure_started_at?: number | null;
  created_at: number;
  error?: string | null;
}

export interface WilsonInterval {
  lower: number;
  upper: number;
  level?: number;
}
