import { expect, test } from "@playwright/test";
import { dragRow, dropFiles, fixtureLibrary, folderId, runId, runningId, uploadId } from "./library-fixtures";

test("file selection, keyboard and inline rename keep names and dates stable", async ({ page }) => {
  const fixture = await fixtureLibrary(page);
  await page.goto("/experiments");
  const alpha = page.getByRole("row", { name: "Alpha result", exact: true });
  const beta = page.getByRole("row", { name: "Beta upload", exact: true });
  await expect(page.getByText("Added", { exact: true })).toBeVisible();
  await expect(page.getByText("Modified", { exact: true })).toHaveCount(0);
  await expect(alpha).toBeVisible();
  await expect(page.getByRole("row", { name: "Gamma running", exact: true })).toHaveCount(0);
  await alpha.click();
  await expect(alpha).toHaveAttribute("aria-selected", "true");
  await expect(page).toHaveURL(/\/experiments$/);
  await beta.click({ modifiers: ["Control"] });
  await expect(page.getByText("2 selected", { exact: true })).toBeVisible();
  await beta.click({ button: "right" });
  await expect(page.getByRole("row", { name: "Alpha result", exact: true, includeHidden: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("row", { name: "Beta upload", exact: true, includeHidden: true })).toHaveAttribute("aria-selected", "true");
  await page.keyboard.press("Escape");
  await beta.press("Escape");
  await alpha.click();
  await beta.click({ modifiers: ["Shift"] });
  await expect(page.getByText("2 selected", { exact: true })).toBeVisible();
  await alpha.press("ArrowDown");
  await expect(beta).toBeFocused();
  await beta.press("Control+a");
  await expect(page.getByText("2 selected", { exact: true })).toBeVisible();
  await alpha.click();
  const date = fixture.state.items[0]!.created_at;
  await alpha.press("F2");
  const name = page.getByRole("textbox", { name: "Display name", exact: true });
  await expect(name).toBeFocused();
  await name.fill("Discard this"); await name.press("Escape");
  await expect(alpha).toBeFocused();
  expect(fixture.calls).toHaveLength(0);
  await alpha.press("F2"); await name.press("Enter");
  await expect(name).toHaveCount(0); expect(fixture.calls).toHaveLength(0);
  await alpha.press("F2"); await name.fill("Commissioning baseline"); await name.press("Enter");
  const renamed = page.getByRole("row", { name: "Commissioning baseline", exact: true });
  await expect(renamed).toBeFocused();
  expect(fixture.state.items[0]!.original_name).toBe("Alpha result.csv");
  expect(fixture.state.items[0]!.created_at).toBe(date);
  fixture.fail("Save failed. Try again.");
  await renamed.press("F2"); await name.fill("Retry baseline"); await name.press("Enter");
  await expect(page.getByRole("alert")).toContainText("Save failed");
  await expect(name).toHaveValue("Retry baseline");
  await page.getByRole("button", { name: "Retry saving name", exact: true }).click();
  await expect(page.getByRole("row", { name: "Retry baseline", exact: true })).toBeVisible();
  // Right-clicking another row selects it; Rename overlays its old name.
  await beta.click({ button: "right" });
  // Base UI hides background content from accessibility while its menu is open.
  await expect(page.getByRole("row", { name: "Beta upload", exact: true, includeHidden: true })).toHaveAttribute("aria-selected", "true");
  await page.getByRole("menuitem", { name: "Rename", exact: true }).click();
  await name.fill("Upload name");
  await page.getByRole("heading", { name: "Experiments", exact: true }).click();
  await expect(page.getByRole("row", { name: "Upload name", exact: true })).toBeVisible();
});

test("folders rename inline, validate duplicate names and retain data on deletion", async ({ page }) => {
  const fixture = await fixtureLibrary(page);
  await page.goto("/experiments");
  await page.getByRole("button", { name: "New folder", exact: true }).filter({ visible: true }).click();
  const name = page.getByRole("textbox", { name: "Folder name", exact: true });
  await name.fill("Pumps"); await name.press("Enter");
  await expect(page.getByRole("alert")).toContainText("already exists");
  await expect(name).toHaveValue("Pumps");
  await name.fill("Motors"); await name.press("Enter");
  await expect(page.getByRole("button", { name: "Motors", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Pumps", exact: true }).press("F2");
  await name.fill("Pump fleet"); await name.press("Enter");
  await expect(page.getByRole("button", { name: "Pump fleet", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Pump fleet", exact: true }).click({ button: "right" });
  await page.getByRole("menuitem", { name: "Delete folder", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("Data and results are retained");
  await page.getByRole("dialog").getByRole("button", { name: "Delete folder", exact: true }).click();
  await expect(page.getByRole("button", { name: "Pump fleet", exact: true })).toHaveCount(0);
  expect(fixture.state.items).toHaveLength(4);
  expect(fixture.state.items.at(-1)!.folder_id).toBeNull();
});

test("native single and selected drag moves, archive protection, restore and failed moves", async ({ page }) => {
  const fixture = await fixtureLibrary(page);
  await page.goto("/experiments");
  const alpha = page.getByRole("row", { name: "Alpha result", exact: true });
  const beta = page.getByRole("row", { name: "Beta upload", exact: true });
  const folder = page.locator(`[data-folder-id="${folderId}"]`);
  await alpha.click(); await beta.click({ modifiers: ["Control"] });
  await dragRow(page, alpha, folder);
  await expect(page.getByRole("status")).toContainText("Moved to Pumps");
  expect(fixture.state.items.filter(item => item.folder_id === folderId)).toHaveLength(3);
  await page.getByRole("button", { name: "Pumps", exact: true }).click();
  const movesBefore = fixture.calls.length;
  await dragRow(page, alpha, folder);
  expect(fixture.calls).toHaveLength(movesBefore);
  await dragRow(page, beta, page.getByRole("button", { name: "Unfiled", exact: true }));
  expect(fixture.state.items.find(item => item.id === uploadId)!.folder_id).toBeNull();
  await page.getByRole("button", { name: "All items", exact: true }).click();
  await page.getByRole("searchbox", { name: "Search this folder", exact: true }).fill("running");
  const running = page.getByRole("row", { name: "Gamma running", exact: true });
  const archivesBefore = fixture.calls.length;
  await dragRow(page, running, page.getByRole("button", { name: "Archive", exact: true }));
  await expect(page.getByRole("alert")).toContainText("Active runs must finish");
  expect(fixture.calls).toHaveLength(archivesBefore);
  await page.getByRole("button", { name: "Clear search", exact: true }).click();
  fixture.fail("Move unavailable. Try again.");
  await dragRow(page, beta, folder);
  await expect(page.getByRole("alert")).toContainText("Move unavailable");
  expect(fixture.state.items.find(item => item.id === uploadId)!.folder_id).toBeNull();
  await dragRow(page, alpha, page.getByRole("button", { name: "Archive", exact: true }));
  await page.getByRole("button", { name: "Archive", exact: true }).click();
  await expect(alpha).toHaveAttribute("draggable", "false");
  await alpha.click();
  await page.getByRole("button", { name: "Restore selected", exact: true }).click();
  expect(fixture.state.items.find(item => item.id === runId)!.folder_id).toBe(folderId);
  expect(fixture.state.items.find(item => item.id === runId)!.archived).toBe(false);
  expect(fixture.state.items.find(item => item.id === runningId)!.archived).toBe(false);
});

test("drag captures selection and pauses polling until it ends", async ({ page }) => {
  const fixture = await fixtureLibrary(page);
  await page.goto("/experiments");
  const alpha = page.getByRole("row", { name: "Alpha result", exact: true });
  await expect(alpha).toBeVisible();
  const transfer = await page.evaluateHandle(() => new DataTransfer());
  await alpha.dispatchEvent("dragstart", { dataTransfer: transfer });
  const reads = fixture.reads();
  await page.waitForTimeout(3300); // Cross the production polling interval while dragging.
  expect(fixture.reads()).toBe(reads);
  await alpha.dispatchEvent("dragend", { dataTransfer: transfer });
  await expect.poll(fixture.reads).toBeGreaterThan(reads);
  await transfer.dispose();
});

test("CSV drops reject unsupported/multiple files, retain failed attachment, retry, cancel and folder context", async ({ page }) => {
  const fixture = await fixtureLibrary(page);
  await page.goto("/experiments");
  const folder = page.locator(`[data-folder-id="${folderId}"]`);
  await expect(folder).toBeVisible();
  await dropFiles(page, folder, ["one.csv", "two.csv"]);
  await expect(page.getByRole("alert")).toContainText("one CSV");
  expect(fixture.uploads()).toBe(0);
  await dropFiles(page, folder, ["notes.txt"]);
  await expect(page.locator(".csv-attachment").getByRole("alert")).toContainText("Choose a CSV");
  await expect(page.getByRole("alert")).toHaveCount(1);
  expect(fixture.uploads()).toBe(0);
  await page.getByRole("button", { name: /Remove notes.txt/ }).click();
  fixture.failUpload(true);
  await dropFiles(page, folder, ["equipment.csv"]);
  await expect(page.getByRole("status").filter({ hasText: "Uploading" })).toBeVisible();
  await expect(page.locator(".csv-attachment").getByRole("alert")).toContainText("Upload unavailable", { timeout: 6000 });
  await expect(page.getByText("equipment.csv", { exact: true })).toBeVisible();
  fixture.failUpload(false);
  const began = Date.now();
  await page.getByRole("button", { name: "Retry upload of equipment.csv", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`dataset=${uploadId}.*folder=${folderId}`), { timeout: 7000 });
  expect(Date.now() - began).toBeGreaterThanOrEqual(3000);
  expect(fixture.calls.filter(call => call.path === "/api/datasets/upload").every(call => call.body.folder === folderId)).toBe(true);
  await page.goto("/experiments");
  await dropFiles(page, page.locator("#library-items"), ["cancel.csv"]);
  await page.getByRole("button", { name: "Cancel CSV upload", exact: true }).click();
  await page.waitForTimeout(3100);
  await expect(page).toHaveURL(/\/experiments$/);
  await expect(page.getByText("cancel.csv", { exact: true })).toHaveCount(0);
});

test("search reveals older items, URLs survive refresh/Back, upload opens with Enter", async ({ page }) => {
  await fixtureLibrary(page);
  await page.goto("/experiments");
  await page.getByRole("searchbox", { name: "Search this folder", exact: true }).fill("Gamma");
  await expect(page.getByRole("row", { name: "Gamma running", exact: true })).toBeVisible();
  await expect(page).toHaveURL(/q=Gamma/);
  await page.reload();
  await expect(page.getByRole("row", { name: "Gamma running", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Pumps", exact: true }).click();
  await expect(page).toHaveURL(/folder=/);
  await page.goBack();
  await expect(page).toHaveURL(/q=Gamma/);
  await page.getByRole("button", { name: "Clear search", exact: true }).click();
  const beta = page.getByRole("row", { name: "Beta upload", exact: true });
  await beta.click(); await beta.press("Enter");
  await expect(page).toHaveURL(new RegExp(`/new\\?source=upload&dataset=${uploadId}`));
  await expect(page.getByRole("heading", { name: "Use your equipment histories", exact: true })).toBeVisible();
});

test("select-all obeys the bulk limit and active selections cannot be archived", async ({ page }) => {
  const fixture = await fixtureLibrary(page);
  const seed = fixture.state.items[0]!;
  fixture.state.items = Array.from({ length: 105 }, (_, index) => ({ ...seed, id: `30000000-0000-4000-8000-${String(index + 100).padStart(12, "0")}`, display_name: `Result ${index + 1}`, status: index === 0 ? "running" : "completed" }));
  await page.goto("/experiments");
  const first = page.getByRole("row", { name: "Result 1", exact: true });
  await first.click(); await first.press("Control+a");
  await expect(page.getByText("100 selected", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Archive selected", exact: true })).toBeDisabled();
  await expect(page.getByText("Active runs must finish before archiving.", { exact: true })).toBeVisible();
  expect(fixture.calls).toHaveLength(0);
  expect(fixture.state.items.some(item => item.archived)).toBe(false);
});

test("stale folders and invalid content/archive drop targets preserve items", async ({ page }) => {
  const fixture = await fixtureLibrary(page);
  await page.goto(`/experiments?folder=10000000-0000-4000-8000-999999999999`);
  await expect(page.getByText("This folder is unavailable. Your items are still in the library.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Show all items", exact: true }).click();
  const alpha = page.getByRole("row", { name: "Alpha result", exact: true });
  const calls = fixture.calls.length;
  await dragRow(page, alpha, page.locator("#library-items"));
  await expect(page.getByRole("alert")).toContainText("Choose a folder or Unfiled");
  expect(fixture.calls).toHaveLength(calls);
  await dropFiles(page, page.getByRole("button", { name: "Archive", exact: true }), ["not-archivable.csv"]);
  await expect(page.getByRole("alert")).toContainText("CSV uploads are unavailable here");
  expect(fixture.uploads()).toBe(0);
  // A stale target can disappear server-side after drag start.
  const transfer = await page.evaluateHandle(() => new DataTransfer());
  await alpha.dispatchEvent("dragstart", { dataTransfer: transfer });
  fixture.state.folders = [];
  const stale = page.locator(`[data-folder-id="${folderId}"]`);
  await stale.dispatchEvent("drop", { dataTransfer: transfer });
  await expect(page.getByRole("alert")).toContainText("This folder is unavailable");
  expect(fixture.state.items.find(item => item.id === runId)!.folder_id).toBeNull();
  await transfer.dispose();
});
