"""Generate the frontend's TypeScript types from the pydantic contract."""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from pydantic import BaseModel  # noqa: E402

from app import schemas  # noqa: E402

OUTPUT = REPO_ROOT / "frontend" / "src" / "api" / "types.ts"

HEADER = """\
// Generated by scripts/generate_types.py from backend/app/schemas.py.
// Do not edit by hand: run `python scripts/generate_types.py` instead.

"""

#: Emitted in dependency-free order; the generator resolves nested models itself.
ROOTS: list[type[BaseModel]] = [
    schemas.DatasetRegistration,
    schemas.DatasetConfirmation,
    schemas.ExperimentCreate,
    schemas.ExperimentRecord,
    schemas.DecisionReport,
    schemas.DatasetProfile,
    schemas.SplitAssignment,
    schemas.CandidateConfig,
    schemas.ScenarioResult,
    schemas.SelectionResult,
    schemas.CalibrationReport,
    schemas.ReplaySeries,
    schemas.AlertExplanation,
    schemas.RunRecord,
    schemas.ReproducibilityCheck,
    schemas.EvidenceBundle,
    schemas.CopilotAnswer,
    schemas.CopilotRequest,
]

SCALARS = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}


def ts_type(node: dict, defs: dict) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]

    if "anyOf" in node or "oneOf" in node:
        options = node.get("anyOf") or node["oneOf"]
        parts = [ts_type(option, defs) for option in options]
        # Collapse duplicates while keeping a stable order.
        seen: list[str] = []
        for part in parts:
            if part not in seen:
                seen.append(part)
        return " | ".join(seen)

    if "const" in node:
        return f'"{node["const"]}"'

    if "enum" in node:
        return " | ".join(f'"{value}"' for value in node["enum"])

    nodeType = node.get("type")
    if nodeType == "array":
        items = node.get("items")
        return f"{ts_type(items, defs)}[]" if items else "unknown[]"
    if nodeType == "object":
        additional = node.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional, defs)}>"
        if node.get("properties"):
            fields = ", ".join(f"{name}: {ts_type(prop, defs)}" for name, prop in node["properties"].items())
            return f"{{ {fields} }}"
        return "Record<string, unknown>"
    if isinstance(nodeType, list):
        return " | ".join(SCALARS.get(t, "unknown") for t in nodeType)
    if nodeType in SCALARS:
        # Dates serialise as ISO strings over the wire.
        if nodeType == "string" and node.get("format") in {"date-time", "date"}:
            return "string"
        return SCALARS[nodeType]
    return "unknown"


def emit_definition(name: str, node: dict, defs: dict) -> str:
    if "enum" in node:
        values = " | ".join(f'"{value}"' for value in node["enum"])
        return f"export type {name} = {values};\n"

    lines = [f"export interface {name} {{"]
    required = set(node.get("required", []))
    for field, prop in node.get("properties", {}).items():
        optional = "" if field in required else "?"
        description = prop.get("description")
        if description:
            wrapped = " ".join(description.split())
            lines.append(f"  /** {wrapped} */")
        lines.append(f"  {field}{optional}: {ts_type(prop, defs)};")
    lines.append("}\n")
    return "\n".join(lines)


def collect() -> tuple[dict[str, dict], list[str]]:
    defs: dict[str, dict] = {}
    order: list[str] = []
    for model in ROOTS:
        schema = model.model_json_schema(mode="serialization")
        for name, node in schema.pop("$defs", {}).items():
            if name not in defs:
                defs[name] = node
                order.append(name)
        name = schema.get("title", model.__name__)
        if name not in defs:
            defs[name] = schema
            order.append(name)
    return defs, order


def main() -> int:
    defs, order = collect()
    # Enums first so the interfaces that reference them read top-down.
    enums = [name for name in order if "enum" in defs[name]]
    interfaces = [name for name in order if "enum" not in defs[name]]

    chunks = [HEADER]
    for name in enums:
        chunks.append(emit_definition(name, defs[name], defs))
    chunks.append("")
    for name in sorted(interfaces):
        chunks.append(emit_definition(name, defs[name], defs))

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(chunks), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}: {len(enums)} enums, {len(interfaces)} interfaces")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
